package intchecker

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"

	"github.com/unxed/f4/vfs"
)

type recordingReporter struct {
	calls     int
	lastTotal int
	files     map[string]bool
}

func (r *recordingReporter) UpdateTransfer(action, filename string, currentPct int, totalText string, totalPct int, speedText string) {
	r.calls++
	r.lastTotal = totalPct
	if r.files == nil {
		r.files = map[string]bool{}
	}
	r.files[filename] = true
	if currentPct < 0 || currentPct > 100 || totalPct < 0 || totalPct > 100 {
		panic("progress out of range")
	}
}

func writeTestFile(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func readTestFile(t *testing.T, dir, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(dir, name))
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

func TestRunGenerateWritesSortedSingleFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "b.txt", "abc")
	writeTestFile(t, dir, "a.txt", "abc")
	if err := os.Mkdir(filepath.Join(dir, "sub"), 0o700); err != nil {
		t.Fatal(err)
	}
	reporter := &recordingReporter{}
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"b.txt", "sub", "a.txt", ".."}, algorithm: AlgSHA256, output: "out.sha256"}
	res, err := runGenerate(context.Background(), job, reporter)
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 2 || len(res.Skipped) != 1 || res.Skipped[0] != "sub" || len(res.Failures) != 0 {
		t.Fatalf("result = %+v", res)
	}
	want := abcDigests[AlgSHA256] + " *a.txt\n" + abcDigests[AlgSHA256] + " *b.txt\n"
	if got := readTestFile(t, dir, "out.sha256"); got != want {
		t.Fatalf("checksum file =\n%q\nwant\n%q", got, want)
	}
	if reporter.lastTotal != 100 || !reporter.files["a.txt"] || !reporter.files["b.txt"] {
		t.Fatalf("progress = %+v", reporter)
	}
}

func TestRunGenerateSkipsItsOwnOutputFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "list.md5", "old")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt", "list.md5"}, algorithm: AlgMD5, output: "list.md5", overwrite: true}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 1 {
		t.Fatalf("result = %+v", res)
	}
	if got, want := readTestFile(t, dir, "list.md5"), abcDigests[AlgMD5]+" *a.txt\n"; got != want {
		t.Fatalf("checksum file = %q, want %q", got, want)
	}
}

func TestRunGenerateDoesNotReplaceUnconfirmedExistingFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "out.md5", "keep me")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(context.Background(), job, &recordingReporter{}); err == nil {
		t.Fatal("existing file replaced without the user's consent")
	}
	if got := readTestFile(t, dir, "out.md5"); got != "keep me" {
		t.Fatalf("existing file changed to %q", got)
	}
}

func TestRunGenerateCancelledWritesNothing(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"a.txt"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(ctx, job, &recordingReporter{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("err = %v, want context.Canceled", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "out.md5")); !os.IsNotExist(err) {
		t.Fatalf("cancelled run left a checksum file: %v", err)
	}
}

func TestRunGenerateReportsMissingFilesAndKeepsTheRest(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"gone.txt", "a.txt"}, algorithm: AlgCRC32, output: "out.sfv"}
	res, err := runGenerate(context.Background(), job, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Written != 1 || len(res.Failures) != 1 || res.Failures[0].Name != "gone.txt" {
		t.Fatalf("result = %+v", res)
	}
	if got, want := readTestFile(t, dir, "out.sfv"), "; Generated by f4\na.txt 352441C2\n"; got != want {
		t.Fatalf("sfv = %q, want %q", got, want)
	}
}

func TestRunGenerateOnlyDirectoriesIsNothingToHash(t *testing.T) {
	dir := t.TempDir()
	if err := os.Mkdir(filepath.Join(dir, "sub"), 0o700); err != nil {
		t.Fatal(err)
	}
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"sub"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(context.Background(), job, &recordingReporter{}); !errors.Is(err, errNothingToHash) {
		t.Fatalf("err = %v, want errNothingToHash", err)
	}
}

func TestRunGenerateEmptyFileHashesToEmptyDigest(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "empty", "")
	job := generateJob{fs: vfs.NewOSVFS(dir), dir: dir, names: []string{"empty"}, algorithm: AlgMD5, output: "out.md5"}
	if _, err := runGenerate(context.Background(), job, &recordingReporter{}); err != nil {
		t.Fatal(err)
	}
	if got, want := readTestFile(t, dir, "out.md5"), "d41d8cd98f00b204e9800998ecf8427e *empty\n"; got != want {
		t.Fatalf("checksum file = %q, want %q", got, want)
	}
}

func TestPercent(t *testing.T) {
	for _, tc := range []struct {
		done, total int64
		want        int
	}{{0, 0, 100}, {0, 10, 0}, {5, 10, 50}, {10, 10, 100}, {11, 10, 100}} {
		if got := percent(tc.done, tc.total); got != tc.want {
			t.Errorf("percent(%d, %d) = %d, want %d", tc.done, tc.total, got, tc.want)
		}
	}
}
