package intchecker

import (
	"bytes"
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/unxed/f4/internal/i18n"
	"github.com/unxed/f4/vfs"
	"github.com/unxed/vtui"
)

func mustHex(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestParseHashFileReadsWhatFormatHashFileWrites(t *testing.T) {
	names := []string{"a.txt", "with space.bin", `back\slash`, "line\nbreak", "sub/dir.txt"}
	for a := range algorithms {
		alg := Algorithm(a)
		var entries []Entry
		for _, name := range names {
			if alg == AlgCRC32 && strings.Contains(name, "\n") {
				continue // SFV cannot store it
			}
			entries = append(entries, Entry{Name: name, Sum: mustHex(t, abcDigests[alg])})
		}
		data, err := FormatHashFile(alg, entries)
		if err != nil {
			t.Fatal(err)
		}
		got, err := ParseHashFile("list"+alg.Extension(), data)
		if err != nil {
			t.Fatalf("%s: %v", alg.Name(), err)
		}
		if got.Algorithm != alg || got.Malformed != 0 || len(got.Entries) != len(entries) {
			t.Fatalf("%s: parsed %+v", alg.Name(), got)
		}
		for i, e := range entries {
			if got.Entries[i].Name != e.Name || !bytes.Equal(got.Entries[i].Sum, e.Sum) {
				t.Errorf("%s: entry %d = %q %x, want %q %x", alg.Name(), i, got.Entries[i].Name, got.Entries[i].Sum, e.Name, e.Sum)
			}
		}
	}
}

func TestParseHashFileAcceptsOtherToolsLines(t *testing.T) {
	md5 := abcDigests[AlgMD5]
	data := "\xef\xbb\xbf# comment\r\n" +
		md5 + "  text mode.txt\r\n" +
		md5 + " single.txt\n" +
		strings.ToUpper(md5) + " *upper.txt\n" +
		"\n   \n" +
		"garbage line\n" +
		md5 + " *\n"
	got, err := ParseHashFile("LIST.MD5", []byte(data))
	if err != nil {
		t.Fatal(err)
	}
	want := []string{"text mode.txt", "single.txt", "upper.txt"}
	if got.Algorithm != AlgMD5 || len(got.Entries) != len(want) || got.Malformed != 2 {
		t.Fatalf("parsed %+v", got)
	}
	for i, name := range want {
		if got.Entries[i].Name != name {
			t.Errorf("entry %d = %q, want %q", i, got.Entries[i].Name, name)
		}
	}
}

func TestParseHashFileReadsSFV(t *testing.T) {
	data := "; Generated by some tool\n" +
		"name with spaces.txt 352441C2\n" +
		"tabbed.txt\t352441c2  \n" +
		"nocrc.txt\n"
	got, err := ParseHashFile("disk.sfv", []byte(data))
	if err != nil {
		t.Fatal(err)
	}
	if got.Algorithm != AlgCRC32 || len(got.Entries) != 2 || got.Malformed != 1 ||
		got.Entries[0].Name != "name with spaces.txt" || got.Entries[1].Name != "tabbed.txt" {
		t.Fatalf("parsed %+v", got)
	}
}

func TestParseHashFilePicksAlgorithmByLength(t *testing.T) {
	for _, tc := range []struct {
		name string
		sum  string
		want Algorithm
	}{
		{"checksums.txt", abcDigests[AlgSHA1], AlgSHA1},
		{"mislabelled.md5", abcDigests[AlgSHA256], AlgSHA256},
		{"noext", abcDigests[AlgSHA384], AlgSHA384},
		{"CHECKSUMS", abcDigests[AlgSHA512], AlgSHA512},
		{"crc.txt", abcDigests[AlgCRC32], AlgCRC32},
	} {
		got, err := ParseHashFile(tc.name, []byte(tc.sum+" *a.txt\n"))
		if err != nil {
			t.Fatalf("%s: %v", tc.name, err)
		}
		if got.Algorithm != tc.want || len(got.Entries) != 1 {
			t.Errorf("%s: algorithm %s, entries %d; want %s", tc.name, got.Algorithm.Name(), len(got.Entries), tc.want.Name())
		}
	}
}

func TestParseHashFileCountsOtherLengthsAsMalformed(t *testing.T) {
	data := abcDigests[AlgMD5] + " *a\n" + abcDigests[AlgSHA1] + " *b\n" + abcDigests[AlgMD5] + " *c\n"
	got, err := ParseHashFile("x.md5", []byte(data))
	if err != nil {
		t.Fatal(err)
	}
	if len(got.Entries) != 2 || got.Malformed != 1 {
		t.Fatalf("parsed %+v", got)
	}
}

func TestParseHashFileErrors(t *testing.T) {
	if _, err := ParseHashFile("x.md5", []byte("; nothing\n\n")); !errors.Is(err, errNoChecksums) {
		t.Fatalf("empty file: err = %v", err)
	}
	if _, err := ParseHashFile("x.txt", []byte("0011223344 *a\n")); !errors.Is(err, errUnknownHashLength) {
		t.Fatalf("5-byte digest: err = %v", err)
	}
	if _, err := ParseHashFile("x.md5", []byte(`\`+abcDigests[AlgMD5]+` *bad\qescape`+"\n")); !errors.Is(err, errNoChecksums) {
		t.Fatalf("bad escape: err = %v", err)
	}
}

func TestChecksumFileNames(t *testing.T) {
	for name, want := range map[string]bool{
		"a.md5": true, "A.SHA256": true, "x.sfv": true, "y.sha384": true, "z.sha512": true, "w.sha1": true,
		".md5": false, "a.txt": false, "md5": false, "a.sha": false,
	} {
		if got := isChecksumFileName(name); got != want {
			t.Errorf("isChecksumFileName(%q) = %v, want %v", name, got, want)
		}
	}
}

// validateFixture is a directory with a.txt ("abc", matches), b.txt (changed
// since), sub/d.txt (matches) and a directory "dir", plus the checksum list
// for a.txt, b.txt, c.txt (missing), dir and sub/d.txt.
func validateFixture(t *testing.T) (string, ChecksumFile) {
	t.Helper()
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "b.txt", "abd")
	if err := os.Mkdir(filepath.Join(dir, "sub"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.Mkdir(filepath.Join(dir, "dir"), 0o700); err != nil {
		t.Fatal(err)
	}
	writeTestFile(t, dir, filepath.Join("sub", "d.txt"), "abc")
	sum := mustHex(t, abcDigests[AlgSHA256])
	file := ChecksumFile{Algorithm: AlgSHA256, Entries: []Entry{
		{Name: "a.txt", Sum: sum},
		{Name: "b.txt", Sum: sum},
		{Name: "c.txt", Sum: sum},
		{Name: "dir", Sum: sum},
		{Name: "sub/d.txt", Sum: sum},
	}}
	return dir, file
}

func TestRunValidateSortsEveryFileIntoAVerdict(t *testing.T) {
	dir, file := validateFixture(t)
	reporter := &recordingReporter{}
	job := validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file}
	res, err := runValidate(context.Background(), job, reporter)
	if err != nil {
		t.Fatal(err)
	}
	want := []entryStatus{statusOK, statusMismatch, statusMissing, statusReadError, statusOK}
	if len(res.Results) != len(want) {
		t.Fatalf("results = %+v", res.Results)
	}
	for i, status := range want {
		if res.Results[i].Name != file.Entries[i].Name || res.Results[i].Status != status {
			t.Errorf("result %d = %+v, want %s %d", i, res.Results[i], file.Entries[i].Name, status)
		}
	}
	if res.Counts != [statusCount]int{2, 1, 1, 1} {
		t.Fatalf("counts = %v", res.Counts)
	}
	if reporter.lastTotal != 100 || !reporter.files["sub/d.txt"] {
		t.Fatalf("progress = %+v", reporter)
	}
}

func TestRunValidateFindsBackslashNames(t *testing.T) {
	dir, _ := validateFixture(t)
	file := ChecksumFile{Algorithm: AlgMD5, Entries: []Entry{{Name: `sub\d.txt`, Sum: mustHex(t, abcDigests[AlgMD5])}}}
	res, err := runValidate(context.Background(), validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file}, &recordingReporter{})
	if err != nil {
		t.Fatal(err)
	}
	if res.Counts[statusOK] != 1 {
		t.Fatalf("results = %+v", res.Results)
	}
}

func TestRunValidateAcceptsAbsoluteNames(t *testing.T) {
	dir, _ := validateFixture(t)
	file := ChecksumFile{Algorithm: AlgMD5, Entries: []Entry{{Name: filepath.Join(dir, "a.txt"), Sum: mustHex(t, abcDigests[AlgMD5])}}}
	other := t.TempDir()
	res, err := runValidate(context.Background(), validateJob{fs: vfs.NewOSVFS(other), dir: other, file: file}, &recordingReporter{})
	if err != nil || res.Counts[statusOK] != 1 {
		t.Fatalf("res = %+v, err = %v", res, err)
	}
}

func TestRunValidateAllMissingAsksForDirectory(t *testing.T) {
	_, file := validateFixture(t)
	empty := t.TempDir()
	_, err := runValidate(context.Background(), validateJob{fs: vfs.NewOSVFS(empty), dir: empty, file: file}, &recordingReporter{})
	if !errors.Is(err, errAllMissing) {
		t.Fatalf("err = %v, want errAllMissing", err)
	}
}

func TestRunValidateCancelled(t *testing.T) {
	dir, file := validateFixture(t)
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := runValidate(ctx, validateJob{fs: vfs.NewOSVFS(dir), dir: dir, file: file}, &recordingReporter{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("err = %v, want context.Canceled", err)
	}
}

func TestValidateReport(t *testing.T) {
	var ok validateResult
	ok.add("a", statusOK, nil)
	ok.add("b", statusOK, nil)
	if got, want := validateReport(ok, 0), fmt.Sprintf(vtui.Msg("IntChecker.AllOK"), 2); got != want {
		t.Fatalf("all OK report = %q, want %q", got, want)
	}

	var bad validateResult
	bad.add("fine", statusOK, nil)
	bad.add("changed", statusMismatch, nil)
	bad.add("broken", statusReadError, errors.New("boom"))
	for i := 0; i < 12; i++ {
		bad.add(fmt.Sprintf("gone%d", i), statusMissing, nil)
	}
	report := validateReport(bad, 3)
	for _, want := range []string{
		fmt.Sprintf(vtui.Msg("IntChecker.ValidateSummary"), 15, 1, 1, 12, 1),
		vtui.Msg("IntChecker.StatusMismatch") + ": changed",
		vtui.Msg("IntChecker.StatusReadError") + ": broken (boom)",
		vtui.Msg("IntChecker.StatusMissing") + ": gone7",
		fmt.Sprintf(vtui.Msg("IntChecker.MoreErrors"), 4),
		fmt.Sprintf(vtui.Msg("IntChecker.Malformed"), 3),
	} {
		if !strings.Contains(report, want) {
			t.Errorf("report lacks %q:\n%s", want, report)
		}
	}
	if strings.Contains(report, "gone8") || strings.Contains(report, ": fine") {
		t.Errorf("report lists too much:\n%s", report)
	}
}

func TestResolveValidateInput(t *testing.T) {
	panelDir := t.TempDir()
	fs := vfs.NewOSVFS(panelDir)
	if _, _, ok := resolveValidateInput(fs, panelDir, "  ", "x"); ok {
		t.Fatal("empty checksum file accepted")
	}
	hashPath, dir, ok := resolveValidateInput(fs, panelDir, " list.md5 ", "")
	if !ok || hashPath != filepath.Join(panelDir, "list.md5") || dir != panelDir {
		t.Fatalf("relative: %q %q %v", hashPath, dir, ok)
	}
	other := t.TempDir()
	abs := filepath.Join(other, "x.sfv")
	hashPath, dir, ok = resolveValidateInput(fs, panelDir, abs, "sub")
	if !ok || hashPath != abs || dir != filepath.Join(panelDir, "sub") {
		t.Fatalf("absolute: %q %q %v", hashPath, dir, ok)
	}
}

// taskAppMock runs progress tasks synchronously and collects messages.
type taskAppMock struct {
	appMock
	messages chan string
}

func (a *taskAppMock) RunAdvancedProgressTask(_ string, _ bool, worker func(context.Context, vfs.TaskReporter) error, onComplete func(error)) {
	onComplete(worker(context.Background(), nopTaskReporter{}))
}

func (a *taskAppMock) Message(_, msg string, _ []string) int {
	a.messages <- msg
	return 0
}

type nopTaskReporter struct{}

func (nopTaskReporter) UpdateScan(string, int64, int64)                         {}
func (nopTaskReporter) UpdateTransfer(string, string, int, string, int, string) {}
func (nopTaskReporter) IsCancelled() bool                                       { return false }

func TestStartValidateReportsResult(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "a.txt", "abc")
	writeTestFile(t, dir, "list.sfv", "a.txt 352441C2\n")
	app := &taskAppMock{messages: make(chan string, 1)}
	fs := vfs.NewOSVFS(dir)
	startValidate(app, fs, filepath.Join(dir, "list.sfv"), dir, autoDetectEncoding)
	if got, want := <-app.messages, fmt.Sprintf(vtui.Msg("IntChecker.AllOK"), 1); got != want {
		t.Fatalf("message = %q, want %q", got, want)
	}
}

func TestStartValidateReportsUnreadableChecksumFile(t *testing.T) {
	dir := t.TempDir()
	writeTestFile(t, dir, "empty.md5", "")
	app := &taskAppMock{messages: make(chan string, 1)}
	fs := vfs.NewOSVFS(dir)
	startValidate(app, fs, filepath.Join(dir, "empty.md5"), dir, autoDetectEncoding)
	if got, want := <-app.messages, fmt.Sprintf(vtui.Msg("IntChecker.NoChecksums"), filepath.Join(dir, "empty.md5")); got != want {
		t.Fatalf("message = %q, want %q", got, want)
	}
	startValidate(app, fs, filepath.Join(dir, "empty.md5"), filepath.Join(dir, "nope"), autoDetectEncoding)
	if got := <-app.messages; got != fmt.Sprintf(vtui.Msg("IntChecker.DirNotFound"), filepath.Join(dir, "nope")) {
		t.Fatalf("message = %q", got)
	}
}

func initValidateTestScreen(t *testing.T) *vtui.ScreenBuf {
	t.Helper()
	vtui.SetDefaultPalette()
	scr := vtui.NewSilentScreenBuf()
	scr.AllocBuf(80, 25)
	vtui.FrameManager.Init(scr)
	return scr
}

func TestStartValidateAsksForDirectoryWhenNothingIsFound(t *testing.T) {
	initValidateTestScreen(t)
	dir := t.TempDir()
	writeTestFile(t, dir, "list.md5", abcDigests[AlgMD5]+" *elsewhere.txt\n")
	app := &taskAppMock{messages: make(chan string, 1)}
	startValidate(app, vfs.NewOSVFS(dir), filepath.Join(dir, "list.md5"), dir, autoDetectEncoding)
	if _, ok := vtui.FrameManager.GetTopFrame().(*vtui.Window); !ok {
		t.Fatalf("top frame = %T, want the directory dialog", vtui.FrameManager.GetTopFrame())
	}
	select {
	case msg := <-app.messages:
		t.Fatalf("unexpected message %q", msg)
	default:
	}
}

// TestValidateDialogDump renders both states of the dialog in English and
// Russian; run with -v to see the text dumps.
func TestValidateDialogDump(t *testing.T) {
	t.Cleanup(func() { i18n.InitLang("", "", "") })
	for _, lang := range []string{"en", "ru"} {
		i18n.InitLang(lang, "en", "")
		for _, note := range []string{"", vtui.Msg("IntChecker.FilesNotFound")} {
			scr := initValidateTestScreen(t)
			d := newValidateDialog(note, "/home/user/photos.md5", "/mnt/cdrom", autoDetectEncoding)
			d.win.Show(scr)
			var dump bytes.Buffer
			scr.Dump(&dump)
			text, _, _ := strings.Cut(dump.String(), "--- CELL METADATA")
			for _, want := range []string{"/home/user/photos.md5", "/mnt/cdrom", strings.ReplaceAll(vtui.Msg("IntChecker.ValidateTitle"), "&", ""),
				strings.ReplaceAll(vtui.Msg("IntChecker.FileEncoding"), "&", "") + " " + vtui.Msg("IntChecker.EncodingAuto")} {
				if !strings.Contains(text, want) {
					t.Errorf("%s dump lacks %q:\n%s", lang, want, text)
				}
			}
			if note != "" && !strings.Contains(text, note) {
				t.Errorf("%s dump lacks the note:\n%s", lang, text)
			}
			t.Logf("%s, note=%v:\n%s", lang, note != "", text)
		}
	}
}
